### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by scavezze** [dan335/cue#1]
I am trying to use the ui helpers

{{> cueStats}} - stats on how long tasks take
{{> cueTasks}} - list of tasks in queue and buttons to manage them
{{> cueJobs}} - list of jobs and buttons to run them

and the package is missing stuff.  moments is one 
i figured that one out.  the next is cueTask is using  {{round numTries}} which dose not work.  also cue Jobs dose not work at all and breaks the route if it's on the page.  I really like this package it's great so far thanks

**Comment by scavezze** [comment]
ReferenceError: ReactiveVar is not defined is what i get when I try and use cueJobs

**Comment by scavezze** [comment]
ok figured out that i need to run 
meteor add reactive-var 
also

**Comment by dan335** [comment]
All fixed, thanks.
